defaults:
  - experimentation: experiment
  - provider: openai
  - tracing: phoenix
  - database: postgres
  - _self_

# top level configuration
logging:
  name: logging.yaml         # logging config file under config/
  notebook: false            # set true to apply logging config inside Jupyter/IPython
